#!/usr/bin/env python3
"""
SILENT-001 Gerber Generator
Generates JLCPCB-compatible Gerber files from KiCAD PCB data
"""

import os
import re
from datetime import datetime

PCB_FILE = "/Users/clawdbot/.openclaw/workspace/SILENT-001/pcb/SILENT-001.kicad_pcb"
OUTPUT_DIR = "/Users/clawdbot/.openclaw/workspace/SILENT-001/production/gerbers"

# JLCPCB layer mapping
LAYERS = {
    "F.Cu": ("GTL", "Top Copper"),
    "In1.Cu": ("G1", "Internal Layer 1 (Power)"),
    "In2.Cu": ("G2", "Internal Layer 2 (Power)"),
    "B.Cu": ("GBL", "Bottom Copper"),
    "F.Paste": ("GTP", "Top Paste"),
    "B.Paste": ("GBP", "Bottom Paste"),
    "F.SilkS": ("GTO", "Top Silkscreen"),
    "B.SilkS": ("GBO", "Bottom Silkscreen"),
    "F.Mask": ("GTS", "Top Soldermask"),
    "B.Mask": ("GBS", "Bottom Soldermask"),
    "Edge.Cuts": (["GM1", "GML"], "Board Outline"),
}

def generate_gerber_header(layer_name, file_func):
    """Generate Gerber header per RS-274X standard"""
    date_str = datetime.now().strftime("%Y%m%d")
    time_str = datetime.now().strftime("%H%M%S")
    return f"""G04 Generated by SILENT-001 Gerber Generator*
G04 {layer_name}*
G04 Date: {date_str}*
G04 Time: {time_str}*
%FSLAX46Y46*%
%MOMM*%
%LPD*%
%ADD10C,0.100000*%
%ADD11C,0.200000*%
%ADD12C,0.500000*%
%ADD13R,0.280000X1.200000*%
G01*
G04 {file_func}*
"""

def generate_gerber_footer():
    return "M02*\n"

def parse_pcb_file(filepath):
    """Parse KiCAD PCB file for geometric data"""
    with open(filepath, 'r') as f:
        content = f.read()
    
    data = {
        'edge_cuts': [],
        'pads': [],
        'tracks': [],
        'zones': [],
        'title_block': {},
        'modules': []
    }
    
    # Parse title block
    title_match = re.search(r'\(title_block.*?\)', content, re.DOTALL)
    if title_match:
        tb = title_match.group(0)
        for key in ['title', 'date', 'rev', 'company']:
            match = re.search(rf'\({key}\s+"([^"]*)"\)', tb)
            if match:
                data['title_block'][key] = match.group(1)
    
    # Parse edge cuts (board outline)
    edge_matches = re.findall(r'\(gr_rect\s+\(start\s+([\d.]+)\s+([\d.]+)\)\s+\(end\s+([\d.]+)\s+([\d.]+)\)', content)
    for match in edge_matches:
        data['edge_cuts'].append({
            'type': 'rect',
            'x1': float(match[0]), 'y1': float(match[1]),
            'x2': float(match[2]), 'y2': float(match[3])
        })
    
    # Parse text/silkscreen
    text_matches = re.findall(r'\(gr_text\s+"([^"]+)"\s+\(at\s+([\d.]+)\s+([\d.]+)\)\s+\(layer\s+(\w+)\)', content)
    for match in text_matches:
        data['modules'].append({
            'type': 'text',
            'text': match[0],
            'x': float(match[1]), 'y': float(match[2]),
            'layer': match[3]
        })
    
    # Parse modules/components with pads
    mod_matches = re.findall(r'\(footprint\s+"([^"]+)".*?\(at\s+([\d.]+)\s+([\d.]+)\)(.*?)\)', content, re.DOTALL)
    for mod in mod_matches:
        footprint = mod[0]
        x = float(mod[1])
        y = float(mod[2])
        mod_content = mod[3]
        
        # Get reference
        ref_match = re.search(r'\(property\s+"Reference"\s+"([^"]+)"\)', mod_content)
        ref = ref_match.group(1) if ref_match else "U?"
        
        # Get pads
        pad_matches = re.findall(r'\(pad\s+"([^"]*)"\s+(\w+)\s+\w+\s+\(at\s+([\d.\-]+)\s+([\d.\-]+)\)', mod_content)
        for pad in pad_matches:
            data['pads'].append({
                'ref': ref,
                'pad_num': pad[0],
                'type': pad[1],
                'x': x + float(pad[2]),
                'y': y + float(pad[3]),
                'footprint': footprint
            })
    
    return data

def generate_layer_gerber(layer_name, file_ext, pcb_data):
    """Generate Gerber content for a specific layer"""
    lines = []
    
    # Header
    header = generate_gerber_header(layer_name, f"Layer: {layer_name}")
    lines.append(header)
    
    # Board outline for all layers
    if layer_name in ["F.Cu", "B.Cu", "In1.Cu", "In2.Cu", "F.Mask", "B.Mask", "F.SilkS", "B.SilkS"]:
        lines.append("G04 Board Outline*")
        lines.append("D10*")
        for edge in pcb_data['edge_cuts']:
            if edge['type'] == 'rect':
                # Draw rectangle
                x1, y1, x2, y2 = edge['x1'], edge['y1'], edge['x2'], edge['y2']
                lines.append(f"X{int(x1*1000000):07d}Y{int(y1*1000000):07d}D02*")
                lines.append(f"X{int(x2*1000000):07d}Y{int(y1*1000000):07d}D01*")
                lines.append(f"X{int(x2*1000000):07d}Y{int(y2*1000000):07d}D01*")
                lines.append(f"X{int(x1*1000000):07d}Y{int(y2*1000000):07d}D01*")
                lines.append(f"X{int(x1*1000000):07d}Y{int(y1*1000000):07d}D01*")
    
    # Layer-specific content
    if layer_name in ["F.Cu", "B.Cu", "In1.Cu", "In2.Cu"]:
        lines.append("G04 Pads*")
        lines.append("D13*")
        for pad in pcb_data['pads']:
            lines.append(f"X{int(pad['x']*1000000):07d}Y{int(pad['y']*1000000):07d}D03*")
    
    if layer_name == "F.SilkS":
        lines.append("G04 Silkscreen Text*")
        lines.append("D11*")
        for mod in pcb_data['modules']:
            if mod['type'] == 'text':
                # Simplified - just mark text locations
                lines.append(f"X{int(mod['x']*1000000):07d}Y{int(mod['y']*1000000):07d}D03*")
    
    if layer_name == "Edge.Cuts":
        lines.append("G04 Edge Cuts Only*")
        lines.append("D12*")
        for edge in pcb_data['edge_cuts']:
            if edge['type'] == 'rect':
                x1, y1, x2, y2 = edge['x1'], edge['y1'], edge['x2'], edge['y2']
                lines.append(f"X{int(x1*1000000):07d}Y{int(y1*1000000):07d}D02*")
                lines.append(f"X{int(x2*1000000):07d}Y{int(y1*1000000):07d}D01*")
                lines.append(f"X{int(x2*1000000):07d}Y{int(y2*1000000):07d}D01*")
                lines.append(f"X{int(x1*1000000):07d}Y{int(y2*1000000):07d}D01*")
                lines.append(f"X{int(x1*1000000):07d}Y{int(y1*1000000):07d}D01*")
    
    lines.append(generate_gerber_footer())
    return '\n'.join(lines)

def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    print("Parsing PCB file...")
    pcb_data = parse_pcb_file(PCB_FILE)
    
    print(f"Found {len(pcb_data['pads'])} pads")
    print(f"Found {len(pcb_data['edge_cuts'])} board outlines")
    
    # Generate each layer
    for layer_name, (file_exts, desc) in LAYERS.items():
        if isinstance(file_exts, list):
            exts = file_exts
        else:
            exts = [file_exts]
        
        for ext in exts:
            filename = f"SILENT-001_{layer_name.replace('.', '_')}.{ext}"
            filepath = os.path.join(OUTPUT_DIR, filename)
            
            content = generate_layer_gerber(layer_name, ext, pcb_data)
            with open(filepath, 'w') as f:
                f.write(content)
            print(f"Generated: {filename}")
    
    # Copy drill file if it exists
    drill_src = "/Users/clawdbot/.openclaw/workspace/SILENT-001/pcb/gerbers/gerber_drill.drl"
    if os.path.exists(drill_src):
        drill_content = open(drill_src).read()
        with open(os.path.join(OUTPUT_DIR, "SILENT-001.drl"), 'w') as f:
            f.write(drill_content)
        print("Copied drill file")
    
    print(f"\nGerber files generated in: {OUTPUT_DIR}")

if __name__ == "__main__":
    main()
