#!/usr/bin/env python3
"""
META-SYSTEM: Automatic GitHub Repository Creator
Creates a new repository for every validated project concept
"""

import json
import os
import subprocess
import sys
from datetime import datetime

# Configuration
GITHUB_API = "https://api.github.com"
WORKSPACE = "/Users/clawdbot/.openclaw/workspace"
REGISTRY_FILE = f"{WORKSPACE}/META_SYSTEM/PROJECT_REGISTRY.json"

def load_registry():
    """Load current project registry"""
    with open(REGISTRY_FILE, 'r') as f:
        return json.load(f)

def save_registry(registry):
    """Save updated registry"""
    registry['last_updated'] = datetime.now().isoformat()
    with open(REGISTRY_FILE, 'w') as f:
        json.dump(registry, f, indent=2)

def create_project_repo(project):
    """Create GitHub repo for a project"""
    project_id = project['id'].lower()
    repo_name = f"{project_id}-research"
    
    # Create local project directory
    project_dir = f"{WORKSPACE}/{project_id}_research"
    os.makedirs(project_dir, exist_ok=True)
    
    # Generate README
    readme_content = f"""# {project['name']}
## Research Project {project['id']}

**Status:** {project['status']}  
**Phase:** {project['phase']}  
**Started:** {project['started']}  
**Success Probability:** {project.get('success_probability', 'TBD')}

### Concept
[To be filled by research agent]

### Critical Blocker
{project.get('critical_blocker', 'None identified yet')}

### Next Action
{project['next_action']}

### Documentation
- Research cycles: See CYCLE_LOG.md
- Technical specs: See SPECS.md
- BOM: See BOM.md

### Timeline
- **Estimated Completion:** {project.get('estimated_completion', 'TBD')}
- **Cycle Interval:** {project.get('cycle_interval_minutes', '15')} minutes

---

*Part of the META-SYSTEM autonomous research consortium*  
*Updated automatically every {project.get('cycle_interval_minutes', '15')} minutes*
"""
    
    with open(f"{project_dir}/README.md", 'w') as f:
        f.write(readme_content)
    
    # Initialize git
    os.chdir(project_dir)
    subprocess.run(['git', 'init'], capture_output=True)
    
    # Create standard files
    with open(f"{project_dir}/CYCLE_LOG.md", 'w') as f:
        f.write(f"# {project['name']} - Research Cycle Log\n\n")
    
    with open(f"{project_dir}/.gitignore", 'w') as f:
        f.write("*.token\n*secret*\n*credential*\n.env\n")
    
    with open(f"{project_dir}/SPECS.md", 'w') as f:
        f.write(f"# {project['name']} - Technical Specifications\n\n[To be populated by research]\n")
    
    with open(f"{project_dir}/BOM.md", 'w') as f:
        f.write(f"# {project['name']} - Bill of Materials\n\n## Components\n\n[To be populated by research]\n")
    
    # Initial commit
    subprocess.run(['git', 'add', '-A'], capture_output=True)
    subprocess.run([
        'git', 'commit', '-m',
        f"Initial commit: {project['name']} research project\n\n"
        f"Status: {project['status']}\n"
        f"Phase: {project['phase']}\n"
        f"Auto-generated by META-SYSTEM"
    ], capture_output=True)
    
    print(f"✓ Created local repo: {project_dir}")
    print(f"✓ Generated template documentation")
    print(f"✓ Ready for GitHub push when token available")
    
    # Update project registry
    project['local_repo_path'] = project_dir
    return project_dir

def main():
    """Main entry point"""
    registry = load_registry()
    
    created = []
    for project in registry['active_projects']:
        if project['id'] and not project.get('local_repo_path'):
            print(f"\n🚀 Initializing {project['id']}: {project['name']}")
            repo_path = create_project_repo(project)
            created.append(project['id'])
    
    if created:
        save_registry(registry)
        print(f"\n✅ Initialized {len(created)} new project repositories")
        for pid in created:
            print(f"  - {pid}")
    else:
        print("\nℹ️ No new projects to initialize")
    
    # Check for projects ready for GitHub
    pending_github = [p for p in registry['active_projects'] 
                      if p.get('local_repo_path') and not p.get('github_repo')]
    
    if pending_github:
        print(f"\n📦 {len(pending_github)} projects ready for GitHub (awaiting token):")
        for p in pending_github:
            print(f"  - {p['id']}: {p['local_repo_path']}")
    
    return 0

if __name__ == "__main__":
    sys.exit(main())
